### ISSUE TITLE
toposortTyVarsOf depends on the order of gensymmed unique values for Names

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/th-desugar#112]
What does this program do?

```haskell
{-# LANGUAGE TemplateHaskell #-}
module Bug where

import Language.Haskell.TH
import Language.Haskell.TH.Desugar

main :: IO ()
main =
  $(do a <- newName "a"
       b <- newName "b"
       runIO $ do putStrLn "toposortTyVarsOf [a,b]"
                  print $ toposortTyVarsOf [DVarT a, DVarT b]
       runIO $ do putStrLn "toposortTyVarsOf [b,a]"
                  print $ toposortTyVarsOf [DVarT b, DVarT a]
       [| return () |])
```

It turns out that both invocations of `toposortTyVarsOf` will return the _same_ answer:

```
$ ghc -package-db ~/.cabal/store/ghc-8.6.3/package.db/ Bug.hs -fforce-recomp
[1 of 1] Compiling Bug              ( Bug.hs, Bug.o )
toposortTyVarsOf [a,b]
[DPlainTV a_6989586621679035542,DPlainTV b_6989586621679035543]
toposortTyVarsOf [b,a]
[DPlainTV a_6989586621679035542,DPlainTV b_6989586621679035543]
```

Yikes! This explicitly goes against the documentation for `toposortTyVarsOf`, which guarantees that it preserves the left-to-right ordering of variables that do not depend on each other.

So why is this happening? When we create a name with `newName`, it is bundled with a gensymmed unique number. The `Ord Name` instance prioritizes this unique over everything else, so if you have `Name`s `a_1` and `b_0` (with respective uniques of 1 and 0), then sorting them according to their `Ord` instance would yield `{b_0, a_1}` (despite the fact that `a` appears before `b` lexicographically).

It turns out that deep within the bowels of `toposortTyVarsOf`, we're constructing a graph using the [`graphFromEdges`](http://hackage.haskell.org/package/containers-0.6.0.1/docs/Data-Graph.html#v:graphFromEdges) function, which uses `Ord` internally! I don't know how I overlooked this originally, but this is the source of all of our troubles.

To further emphasize how dangerous `toposortTyVarsOf`'s current behavior is, if you compile the program above with `-dunique-increment=-1`, you'll get a completely different answer:

```
$ ghc -package-db ~/.cabal/store/ghc-8.6.3/package.db/ Bug.hs -fforce-recomp -dunique-increment=-1
[1 of 1] Compiling Bug              ( Bug.hs, Bug.o )
toposortTyVarsOf [a,b]
[DPlainTV b_7061644215716911977,DPlainTV a_7061644215716911978]
toposortTyVarsOf [b,a]
[DPlainTV b_7061644215716911977,DPlainTV a_7061644215716911978]
```

~~Patch incoming.~~ (**EDIT**: See https://github.com/goldfirere/th-desugar/issues/112#issuecomment-461990221.)

**Comment by RyanGlScott** [comment]
Hm, I just realized that fixing this would require much more effort than I originally expected, since `toposortTyVarsOf` also uses `Set.toList`, making it even more non-deterministic. I'll park this for now and nab this later when fixing goldfirere/singletons#367.

**Comment by goldfirere** [comment]
See also GHC's `scopedSort` in the `Type` module.

**Comment by RyanGlScott** [comment]
Funny you mention that, since I literally copied `scopedSort` to fix a [similar issue in `th-abstraction`](https://github.com/glguy/th-abstraction/pull/71). (Sadly, `scopedSort` alone isn't enough to fix this issue in `th-desugar` due to https://github.com/goldfirere/th-desugar/issues/112#issuecomment-461990221.)
