### ISSUE TITLE
Should DInstanceD have a Maybe [DTyVarBndr] field?

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/th-desugar#117]
This is the current definition of `DInstanceD`:

https://github.com/goldfirere/th-desugar/blob/e420eaeb80f108c186c26ea706c7d80ce5e3d106/Language/Haskell/TH/Desugar/AST.hs#L94

This makes sense, as it mirrors `InstanceD` in `template-haskell`. However, I'm wondering if the API might be made more complete by adding an additional field to `DInstanceD` of type `Maybe [DTyVarBndr]`. This idea was born out of a realization I had when I thought about instances like the one below (inspired by [GHC #16518](https://gitlab.haskell.org/ghc/ghc/issues/16518)):

```hs
class HTestEquality (f :: forall k. k -> Type) where
  hTestEquality :: forall k1 k2 (a :: k1) (b :: k2).
                   f a -> f b -> Maybe (a :~~: b)
newtype T :: (forall k. k -> Type) -> (forall k. k -> Type) where
  MkT :: forall (f :: forall k. k -> Type) k (a :: k). f a -> T f a

instance forall (f :: forall k. k -> Type). HTestEquality f => HTestEquality (T f) where
  hTestEquality (MkT x) (MkT y) = hTestEquality x y
```

How exactly would one represent `instance forall (f :: forall k. k -> Type). HTestEquality f => HTestEquality (T f)` in Template Haskell? There's not an obvious place to put the `forall (f :: forall k. k -> Type)` part, and if we omit it, then the instance will fail to typecheck. Luckily, there _is_ a way to accomplish this: use the following TH AST:

```
λ> ; $(newName "f" >>= \f -> newName "k" >>= \k -> pure [InstanceD Nothing [] (ForallT [KindedTV f (ForallT [PlainTV k] [] (ArrowT `AppT` VarT k `AppT` StarT))] [ConT ''HTestEquality `AppT` VarT f] (ConT ''HTestEquality `AppT` (ConT ''T `AppT` VarT f))) []])
<interactive>:33:5-254: Splicing declarations
    newName "f"
      >>=
        \ f_ahqw
          -> newName "k"
               >>=
                 \ k_ahqx
                   -> pure
                        [InstanceD
                           Nothing
                           []
                           (ForallT
                              [KindedTV
                                 f_ahqw
                                 (ForallT
                                    [PlainTV k_ahqx] [] (ArrowT `AppT` VarT k_ahqx `AppT` StarT))]
                              [ConT ''HTestEquality `AppT` VarT f_ahqw]
                              (ConT ''HTestEquality `AppT` (ConT ''T `AppT` VarT f_ahqw)))
                           []]
  ======>
    instance forall (f_ahrt :: forall k_ahru.
                               k_ahru -> Data.Kind.Type).
             HTestEquality f_ahrt => HTestEquality (T f_ahrt)
```

This trick is a bit grimy, but it has the nice property that we don't have to change the TH AST to accommodate the (relatively obscure) use case of higher-ranked kind variables. Instead, we only need make this change in the downstream `th-desugar` library by adding a field of type `Maybe [DTyVarBndr]` to `DInstanceD`. If that field is instantiated with `Just tvs`, then we use the trick above and explicitly quantify `tvs`. If it's `Nothing`, then proceed like we normally do.

If we extend `DInstanceD`, then we should also give `DStandaloneDerivD` the same treatment.

**Comment by goldfirere** [comment]
I'm in favor of this change in th-desugar. But should we also do this in TH proper? Currently, a TH quote just forgets the `forall`.

**Comment by RyanGlScott** [comment]
Perhaps. But I'm really disinclined to make yet another huge breaking change to Template Haskell unless we have a Very Good Reason to do so, and given that there's a suitable workaround (documented above), I don't think this change meets that threshold.

**Comment by goldfirere** [comment]
Okidoki. Full steam ahead on th-desugar, then.

**Comment by RyanGlScott** [comment]
Bad news: this `forall` trick isn't supported on exactly one version of GHC that `th-desugar` currently supports: GHC 8.0.2.

```
Test/DsDec.hs:77:3: error:
    Malformed instance: forall a. S.ExCls (S.ExData a)
```

Less critically, using this trick with GHC 7.10.3 in a standalone `deriving` declaration causes GHC to freak out a bit:

```
[2 of 4] Compiling Dec              ( Test/Dec.hs, /home/rgscott/Documents/Hacking/Haskell/staging/th-desugar/dist-newstyle/build/x86_64-linux/ghc-7.10.3/th-desugar-1.10/t/spec/build/spec/spec-tmp/Dec.o )
Var/Type length mismatch: 
  [a_acV1]
  []
Var/Type length mismatch: 
  [a_acV1]
  []
[3 of 4] Compiling DsDec            ( Test/DsDec.hs, /home/rgscott/Documents/Hacking/Haskell/staging/th-desugar/dist-newstyle/build/x86_64-linux/ghc-7.10.3/th-desugar-1.10/t/spec/build/spec/spec-tmp/DsDec.o )
Var/Type length mismatch: 
  [a_acV1]
  []
Var/Type length mismatch: 
  [a_acV1]
  []
```

This is rather annoying, since it's not the oldest versions of GHC giving us problems, but rather versions that are smack-dab in the middle of the range of versions that `th-desugar` supports. Some possible remedies:

* We could prohibit using this trick unless GHC 8.2 or later is used, although that cuts off certain versions of GHC where this trick works perfectly well.
* Alternatively, we could throw an error when using this trick on the particular versions of GHC where it's known to break.
* Something else?

Thoughts?

**Comment by goldfirere** [comment]
I support

> Alternatively, we could throw an error when using this trick on the particular versions of GHC where it's known to break.

It's annoying, but not terribly hard to do this. Of course, the error gets thrown only when the broken feature gets used.

Thanks!
