### ISSUE TITLE
Adapt to explicit specificity in th-desugar

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/th-desugar#140]
Now that GHC HEAD implements support for explicit specificity in `template-haskell`, the next step is to figure out how to fold these changes into `th-desugar` itself. Let me go through the explicit specificity patch part-by-part:

* First, the patch changed `TyVarBndr` to become parameterized by a `spec` type parameter:

  ```hs
  data TyVarBndr flag = PlainTV  Name flag
                      | KindedTV Name flag Kind

  type TyVarBndrUnit = TyVarBndr ()
  type TyVarBndrSpec = TyVarBndr Specificity
  ```
  
  Where `Specificity` is defined as:
  
  ```hs
  data Specificity = SpecifiedSpec
                   | InferredSpec
  ```

  I envision that the exact same changes will need to be made on `th-desugar`'s side, but with `DTyVarBndr` instead of `TyVarBndr`.
* Nest, the patch changed various constructors to use `TyVarBndrUnit`, such as `RuleP`, `DataD`, `TySynD`, etc. Again, no real surprises here—we'll need to mirror these changes in `DRuleP`, `DDataD`, `DTySynD`, etc.
* Lastly, the patch changed two very important `Type` constructors:

  ```hs
  data Type = ForallT [TyVarBndr Specificity] Cxt Type
            | ForallVisT [TyVarBndr ()] Type
            | ...
  ```

  This will be the trickiest part to adapt to in `th-desugar`, as `th-desugar` picks a different representation for `forall`s. Currently, it's:

  ```hs
  data DType = DForallT ForallVisFlag [DTyVarBndr] DType
             | ...
  ```

-----

How should `DType` be changed to accommodate `Specificity`? Two ideas:

1. Do what the GHC API's `HsType` does: just use `DTyVarBndrSpec`:

   ```hs
   data DType = DForallT ForallVisFlag [DTyVarBndrSpec] DType
              | ...
   ```

   I'm personally somewhat uneasy about doing this, since this introduces an unrepresentation state: you can combine `ForallInvis` with `InferredSpec`. But then again, the GHC API has this exact same unrepresentable state.
2. Split `DForallT` into two constructors:

   ```hs
   data DType = DForallT [DTyVarBndrSpec] DType
              | DForallVisT [DTyVarBndrUnit] DType
              | ...
   ```

   Alternatively, if you'd prefer factoring out the second argument, the following would also work:

   ```hs
   data DType = DForallT DForallTelescope DType
              | ...

   data DForallTelescope
     = DForallVis   [DTyVarBndrUnit]
     | DForallInvis [DTyVarBndrSpec]
   ```

   This avoids the unrepresentable state in the first design.

**Comment by goldfirere** [comment]
I vote (2) for the same reasons you seem to prefer it. Agnostic on whether we want the original idea or the alternative.

**Comment by RyanGlScott** [comment]
I'm leaning towards `DForallTelescope`, if only because we have another data type that must make a distinction between visible and invisible `forall`s: [`DFunArgs`](https://hackage.haskell.org/package/th-desugar-1.11/docs/Language-Haskell-TH-Desugar.html#t:DFunArgs).

```hs
data DFunArgs
  = DFANil
  | DFAForalls ForallVisFlag [DTyVarBndr] DFunArgs
  | DFACxt DCxt DFunArgs
  | DFAAnon DType DFunArgs
```

With `DForallTelescope`, we can adapt `DFunArgs` quite easily:

```diff
-  | DFAForalls ForallVisFlag [DTyVarBndr] DFunArgs
+  | DFAForalls DForallTelescope DFunArgs
```

Alternatively, we could split up `DFAForalls` into two constructors, much like we could split up `DForallT` into two constructors. But the possibility of sharing a common data type instead is just too appealing to pass up.

(As an aside, I wonder if we should adopt a similar trick in GHC's `HsForAllTy`? I think that would eliminate the unrepresentable state there as well.)

**Comment by goldfirere** [comment]
I like it -- including in GHC if you should like to make the change there.

**Comment by RyanGlScott** [comment]
I tried prototyping this in GHC, and it went pretty well. See [GHC#18235](https://gitlab.haskell.org/ghc/ghc/issues/18235)/[GHC!3352](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/3352).
