### ISSUE TITLE
Adapt to linear types in th-desugar

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/th-desugar#143]
How should `th-desugar` cope with a brave new linear world? At first glance, the changes that the [linear types patch](https://gitlab.haskell.org/ghc/ghc/-/commit/40fa237e1daab7a76b9871bb6c50b953a1addf23) makes to `template-haskell` might seem deceptively small:

```diff
@@ -2465,6 +2468,7 @@ data Type = ForallT [TyVarBndr Specificity] Cxt Type -- ^ @forall \<vars\>. \<ct
           | UnboxedTupleT Int             -- ^ @(\#,\#), (\#,,\#), etc.@
           | UnboxedSumT SumArity          -- ^ @(\#|\#), (\#||\#), etc.@
           | ArrowT                        -- ^ @->@
+          | MulArrowT                     -- ^ @FUN@
           | EqualityT                     -- ^ @~@
           | ListT                         -- ^ @[]@
           | PromotedTupleT Int            -- ^ @'(), '(,), '(,,), etc.@
```

The ramifications for `th-desugar` could be larger, however. Some questions we must answer are:

1. How should `DType` be changed? We could simply add a new `DMulArrowT` constructor alongside `DArrowT`, but that might fall afoul of the general `th-desugar` principle of making the AST "minimalist". Perhaps a better design is possible.
2. How should `DFunArgs` be changed? Currently, we have:

   ```hs
   data FunArgs
     = ...
     | DFAAnon DType DFunArgs
   ```

   `DFAAnon` doesn't record whether the argument to a function arrow is linear or not. We probably should, somehow.
3. How should `L.H.TH.Desugar.Reify` deal with reifying the types of data constructors? Haskell98 constructors and record GADT constructors are easy, since they will always have linear argument types (e.g., `Just :: a #-> Maybe a`). The tricky case will be prefix GADT constructors, which can have mixed linear and unrestricted arguments. To make things worse, GHC makes it difficult to know which are which. See [GHC#18378](https://gitlab.haskell.org/ghc/ghc/-/issues/18378). We might have to settle for heuristics here.

**Comment by goldfirere** [comment]
Good question.

1. In `th-desguar`'s minimalist style, I think we should have a `DFunT` constructor that corresponds exactly to `FUN`. No more `DArrowT`, which can easily be expressed in terms of `FUN`.

2. You're right. `DFAAnon` should also store the multiplicity of the argument.

3. Let's assume that GHC#18378 will be fixed before release. Then I think this problem becomes straightforward.

**Comment by RyanGlScott** [comment]
> 1. In `th-desguar`'s minimalist style, I think we should have a `DFunT` constructor that corresponds exactly to `FUN`. No more `DArrowT`, which can easily be expressed in terms of `FUN`.

Interesting. I wonder if it would make sense to just represent `FUN` as `ConT ''Fun`? After all, we don't have a special AST form for `TYPE`. (Disclaimer: I have not implemented this idea yet.)

> 3. Let's assume that GHC#18378 will be fixed before release. Then I think this problem becomes straightforward.

I have to wonder if this really will be fixed in time for 8.12. I'm reminded of a comment you made about a different TH-related ticket [here](https://github.com/goldfirere/th-desugar/issues/113#issuecomment-470278994):

> My musings in GHC#16396 are a roundabout way of suggesting that we change `ForallT` to be more sensible. But I didn't want to just come out and say it, because that's the wrong way around: my motivation is that the current behavior causes bugs that (I think) are structurally impossible to avoid without changing `ForallT`.

Similarly, my musings in [GHC#18378](https://gitlab.haskell.org/ghc/ghc/-/issues/18378) are a roundabout way of suggesting that we change `GadtC` to be more sensible. Currently, we have:

```hs
data Con
  = ...
  | GadtC [Name] [BangType] Type
```

As far as a I can tell, there is no sensible way for today's `GadtC` to remember whether an argument (represented with a `BangType`) is linear or not, so GHC has to guess whether it's linear or not when splicing in a `GadtC`. Based on the results of GHC#18378, it appears that GHC errs on the side of linearity.

Just like you didn't want to just come out and say it, _I_ didn't want to come and say that `GadtC` should be changed either.

**Comment by goldfirere** [comment]
> Interesting. I wonder if it would make sense to just represent `FUN` as `ConT ''Fun`? After all, we don't have a special AST form for `TYPE`. (Disclaimer: I have not implemented this idea yet.)

This is reasonable. I think I remember considering the same question when making `DArrowT`, which could of course be `DConT ''(->)`. I decided that `singletons` would be easier to write with `DArrowT`, so that factor powered the design decision. I think the same reasoning is applicable here: what would make `singletons`'s life easier? I think you're the best judge of that, and I wouldn't want a foolish consistency ("minimalism") to become a hobgoblin. (Of course, we have clients other than `singletons`, but I still think this is a fine way of making a borderline design decision.)

> 
> > 1. Let's assume that GHC#18378 will be fixed before release. Then I think this problem becomes straightforward.
> 
> I have to wonder if this really will be fixed in time for 8.12. I'm reminded of a comment you made about a different TH-related ticket [here](https://github.com/goldfirere/th-desugar/issues/113#issuecomment-470278994):
> 
> > My musings in GHC#16396 are a roundabout way of suggesting that we change `ForallT` to be more sensible. But I didn't want to just come out and say it, because that's the wrong way around: my motivation is that the current behavior causes bugs that (I think) are structurally impossible to avoid without changing `ForallT`.
> 
> Similarly, my musings in [GHC#18378](https://gitlab.haskell.org/ghc/ghc/-/issues/18378) are a roundabout way of suggesting that we change `GadtC` to be more sensible. Currently, we have:
> 
> ```haskell
> data Con
>   = ...
>   | GadtC [Name] [BangType] Type
> ```
> 
> As far as a I can tell, there is no sensible way for today's `GadtC` to remember whether an argument (represented with a `BangType`) is linear or not, so GHC has to guess whether it's linear or not when splicing in a `GadtC`. Based on the results of GHC#18378, it appears that GHC errs on the side of linearity.
> 
> Just like you didn't want to just come out and say it, _I_ didn't want to come and say that `GadtC` should be changed either.

Thoughts on `GadtC` evolved considerably during yesterday's call. But I forget exactly where they ended up, and on what timeline. I seem to recall thinking that the problem wouldn't be fixed for 8.12, but that we would be sound in the absence of linear types. This is a reasonable resting place: if TH doesn't have full support for linear types in 8.12, th-desugar certainly can't. Maybe, then, it's best to have no support at all for linear types, and if the desugaring process spots a linear type, it just fails.

**Comment by RyanGlScott** [comment]
> I think the same reasoning is applicable here: what would make `singletons`'s life easier?

At this point, I'm not really sure. It's certainly not unreasonable to include a special constructor for function types—if Core can do, then so can anyone else. But I haven't yet tried a design without a special constructor for comparison.

> Maybe, then, it's best to have no support at all for linear types, and if the desugaring process spots a linear type, it just fails.

Ah, that is an intriguing possibility. Alas, we can't just fail whenever we see a linear type, since the design of the linear types patch makes linear types pervasive, even in code that doesn't explicitly enable the `LinearTypes` extension. For instance, reifying the type of `Just` will produce `a #-> Maybe a`. We'd likely have to desugar `(#->)` to `(->)` to make this plan work.

**Comment by goldfirere** [comment]
I am fine with that plan. It should be documented carefully in the release notes, but I think it's reasonable just to ignore linearity.
