### ISSUE TITLE
Use `DeriveLift` instead of TH to define `Lift` instances

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/th-desugar#176]
Currently, all of the `Lift` instances in `th-desugar` are defined as orphans in a separate [`Language.Haskell.TH.Desugar.Lift`](https://github.com/goldfirere/th-desugar/blob/92c07bd88b74efae0d1b6b7bb5d52049723a009a/Language/Haskell/TH/Desugar/Lift.hs) module. Historically, this made sense, as it also defined orphan instances for external data types in the `template-haskell` library. Nowadays, this is no longer the case, as it simply relies on [`th-orphans`](https://hackage.haskell.org/package/th-orphans) to obtain `Lift` instances for the `template-haskell` library.

Moreover, all of the instances in `Language.Haskell.TH.Desugar.Lift` are defined using Template Haskell by way of the [`th-lift`](https://hackage.haskell.org/package/th-lift) library. Nowadays, this is overkill, as we can just as well use the `DeriveLift` language extension to accomplish the same thing without TH. `DeriveLift` was first introduced in GHC 8.0, which is now the minimum GHC version that `th-desugar` supports.

I propose replacing all of the TH-based instances in `Language.Haskell.TH.Desugar.Lift` with ones generated using `DeriveLift`. There is one complication with this plan, however: the `th-desugar` AST relies on the [`Specificity` compatibility shim](https://github.com/glguy/th-abstraction/blob/3227c489993bd2f5340f69a4ecbeb863be077b81/src/Language/Haskell/TH/Datatype/TyVarBndr.hs#L98-L101) from the [`th-abstraction`](https://hackage.haskell.org/package/th-abstraction) library on pre-9.0 versions of GHC, and that shimmed data type does not define a `Lift` instance. The most direct solution to this issue would be to define a `Lift` instance in the `th-abstraction` library—I've opened glguy/th-abstraction#97 for this.

**Comment by goldfirere** [comment]
Switching to use DeriveLift instead of TH sounds like a definite win, to me.

**Comment by RyanGlScott** [comment]
[`th-abstraction-0.5.0.0`](https://hackage.haskell.org/package/th-abstraction-0.5.0.0) includes a `Lift` instance for `Specificity`, so we now have everything that we need to fix this issue.
