### ISSUE TITLE
Local reification fails on infix data family

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/th-desugar#184]
Surprisingly, this fails:

```hs
{-# LANGUAGE GADTs #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
module Bug where

import Language.Haskell.TH.Desugar

$(do decs <- [d| data family x ^^^ y
                 data instance x ^^^ y = Blah x y
               |]
     decs' <- dsDecs decs
     pure (sweeten decs'))
```
```
[1 of 1] Compiling Bug              ( Bug.hs, interpreted )

Bug.hs:9:2: error: Unexpected data instance LHS: (x_0 ^^^_1 y_2)
  |
9 | $(do decs <- [d| data family x ^^^ y
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

If I change `x ^^^ y` to `(^^^) x y`, however, then it succeeds. I suspect that this is due to a buglet in the implementation of `unfoldType`:

https://github.com/goldfirere/th-desugar/blob/a4d188c7f00fcbc2a345514833f193fa4b6bd1c8/Language/Haskell/TH/Desugar/Util.hs#L313-L324

In particular, there is a missing case for `InfixT`, and as a result, the arguments to the infix `^^^` type constructor are never split apart. I think we should add a case like this:

```hs
   go acc (InfixT ty1 n ty2) = go (TANormal ty1:TANormal ty2:acc) (ConT n)
```

**Comment by goldfirere** [comment]
Yes, I agree with your diagnosis and suggested fix.
