### ISSUE TITLE
GHC Head won't compile

### ISSUE THREAD

**Issue by ggreif** [goldfirere/th-desugar#33]
Fixity removed from various constructors
Open/closed type families (FamilyD gone)

**Comment by goldfirere** [comment]
Thanks for reporting. I'm not going to fix this right now, because I'm planning a bunch more changes in TH before 8.0 comes out. But I'll keep the ticket open to track those updates once the new TH hits.

**Comment by goldfirere** [comment]
Note to self: double-check PR #35.

**Comment by goldfirere** [comment]
All set now. Some tests may fail with the release candidates, but it should all get smoothed out before the real release.
