### ISSUE TITLE
Documentation missing on hackage for version 1.6

### ISSUE THREAD

**Issue by expipiplus1** [goldfirere/th-desugar#41]
It might be worth uploading the documentation manually as hackage seems to have stalled.

**Comment by goldfirere** [comment]
Bah. See my comment on haskell/hackage-server#295.

Thanks for alerting me to the problem!

**Comment by goldfirere** [comment]
I guess I should be more patient. It just took Hackage a little while to update. All set now.

**Comment by expipiplus1** [comment]
thanks!
