### ISSUE TITLE
Desugar all datatypes and constructors to GADT syntax

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/th-desugar#68]
As discussed in #65, the current `th-desugar` AST for datatypes (`DDataD` and `DDataInstD`) cannot express return kinds, such as `data Foo :: forall j. j -> forall k. k -> Type`. It would be natural to add this, but we wish to do so in a way that maintains a minimal surface API. The coexistence of H98 and GADT syntax complicates this story significantly, so we decided in #65 to solve this problem by desugaring _all_ datatypes (and constructors) to GADT syntax, as GADT syntax is a generalization of H98 syntax.

I'm opening this issue because as I attempted to implement this, there were a number of tricky design questions I stumbled upon that I'd be interested in hearing feedback about. Namely:

1. Should we store the return kind of a datatype as `Maybe DKind` or `DKind`? GADT syntax allows for either, but if a return kind is left off, we know that it simply defaults to `Type`, so we could just desugar to `Type` in the absence of an explicit return kind. (Contrast this with `DFamilyResultSig`, which has an explicit `NoSig` form.)
2. How should we store the quantified type variables in each constructor? Currently, `DCon` has a simple `[DTyVarBndr]` field that doesn't state any properties about _what_ type variables it holds. When transitioning everything over to use GADT syntax, however, it becomes less clear what this `[DTyVarBndr]` field does. Does it:

   * Store only the existentially quantified type variables?
   * Store all of the universally quantified type variables in the front of the list, followed by all of the existentially quantified type variables? (Or perhaps we should have two separate lists for the universals and existentials?)

   My inclination is the second option, as there are several spots in `th-desugar` where it's convenient to pluck out the universally quantified type variables (for instance, I need these when sweetening a `DCon` to a `ForallC` on old GHCs).

3. What becomes of the `[DTyVarBndr]` field of `DDataD`/`DDataInstD`? Before, it served double-duty as both the (universal) tyvars of the data type constructor, as well as a syntactic representation of what the user wrote. But if we throw explicit return kinds in the mix, that's no longer true. For instance:

   ```haskell
   data Either (a :: Type) :: Type -> Type where
     Left  :: a -> Either a b
     Right :: b -> Either a b
   ```

   Here, the tyvars of the `Either` tycon are `[a,b]`, but that's _not_ what's shown syntactically (just `[a]`). So the question becomes: should this `[DTyVarBndr]` field show _all_ of the data type constructor's tyvars, or only the ones that were written out syntactically?

**Comment by goldfirere** [comment]
> Should we store the return kind of a datatype as `Maybe DKind` or `DKind`? 

Good question. I think it should be `Maybe DKind`, because the presence/absence of a kind signature can change whether GHC thinks the type has a CUSK. (I hate CUSKs.) Contrariwise, I'm not sure we really need `NoSig` for type families. But perhaps we don't need to ruffle those feathers today.

> How should we store the quantified type variables in each constructor?

I think we need to store all the variables (or none of them). Anything else is an error. I doubt GHC will accept double foralls here, as constructor syntax is a little picky.

> What becomes of the `[DTyVarBndr]` field of `DDataD`/`DDataInstD`? 

It continues to represent what appears syntactically. Note that these are not redundant:

```
data F k :: k -> Type
```

cannot be written without that first `k`.

Thanks!

**Comment by RyanGlScott** [comment]
> I think we need to store all the variables (or none of them). Anything else is an error. I doubt GHC will accept double foralls here, as constructor syntax is a little picky.

To be clear, I'm not saying we should have two `[DTyVarBndr]` fields and interpret them as `forall <univs>. forall <exis>. ...`. Rather, we should interpret the two `[DTyVarBndr]` fields as `forall (<univs> ++ <exis>). ...`. Having the universally quantified type variables separate from the existentially quantified ones is purely for the sake of convenience.

To better motivate why I want to do this, consider the [`getRecordSelectors`](https://github.com/goldfirere/th-desugar/blob/afeab520b3300fb1b79f6390dbf0741223d5de67/Language/Haskell/TH/Desugar.hs#L231-L252) function. This detects "naughty" record selectors (those which have existential type variables in their type signatures) by using ```fvDType field_type `isSubsetOf` data_ty_con_ty_vars```. But under this new proposed design, there's a problem: the universal type variables in `field_type` might be completely different from those in `data_ty_con_ty_vars`, since the type variables in `field_type` are scoped differently! So it's convenient to be able to quickly differentiate between the universals and the existentials in each constructor signature (otherwise, you'd have to calculate this yourself, which is awkward).

> It continues to represent what appears syntactically. Note that these are not redundant:
>
> ```
> data F k :: k -> Type
> ```
>
> cannot be written without that first k.

To be clear, what I'm asking here is: should we have the `[DTyVarBndr]` field represent _all_ tyvar binders in the data tycon, or _only_ the syntactic ones? In your `data F` example, we have two choices:

* `[k, a]` (where `(a :: k)` comes from the `k -> Type` return kind)
* `[k]`

With the former option, we can immediately look up the universal type variables of a datatype without needing to descend into a constructor (indeed, it might not have any constructors!), but we lose some syntactic information. (The tradeoffs for the latter option are in the opposite directions.)

**Comment by goldfirere** [comment]
Consider

```
data F a b :: forall k. k -> Type
```

That type cannot be written without the `::`, because the kind quantification comes late in the declaration. So we have cases where we can't move the `::` left and cases where we can't move it right. That tells me that we just keep it where it is. :)

As for univs and exs, we can't reliably do that for constructors declared with GADT syntax. For example:

```
data S a where
  MkS :: forall k (a :: k). S a
```

If we just look at the return type from `MkS`, it looks like `k` is existential. But it isn't really. So any purely syntactic check will fail. (Likely including your naughty-record-selector check.) And if we can't do univs vs exs for some types, we shouldn't bother to do it for any.

**Comment by RyanGlScott** [comment]
The reason I'm making such a stink about the universal/existential distinction is because it has important practical consequences. I'll again focus on the [`getRecordSelectors`](https://github.com/goldfirere/th-desugar/blob/afeab520b3300fb1b79f6390dbf0741223d5de67/Language/Haskell/TH/Desugar.hs#L231-L252) function, which is what made me realize the importance of this design consideration.

`getRecordSelectors`, as part of its workload, detects "naughty" record selectors (those which have existential type variables in their type signatures). Currently, this works due to a lucky fluke (on H98-style datatypes, at least), since the type variables in the data type constructor and in the fields of the constructor itself happen to be shared, so we can find existentially quantified type variables by finding ones that aren't among the data type constructors' type variables. But for GADTs, this doesn't hold, since any type variables in the type of a constructor's field can be differently scoped from the data type constructors' variables! This means that in order to make `getRecordSelectors` for GADTs (or indeed, for _any_ data type, under this new proposal), we'd need a different plan.

Thus the ability to look up the set of universal type variables isn't me just trying to be annoying—`th-desugar` won't work without it.

**Comment by goldfirere** [comment]
I didn't think it was annoying. I agree with you. But it's possible there's no way to do what you want, short of type inference. Perhaps we go with the two `TyVarBndr`s, but on GADT-syntax constructors, it's more of a best guess.

**Comment by RyanGlScott** [comment]
> But it's possible there's no way to do what you want, short of type inference.

Indeed, type inference is the elephant in the room. And now that I think on it more, there's many additional challenges to trying to maintain a universal/existential distinction at the Template Haskell level. For instance:

```haskell
data Foo (a :: k) where
  MkFoo :: Foo Int
```

To do this right, we'd need to put `k` and `a` as universal type variables in `MkFoo`, and moreover, we'd need to infer that `k ~ Type`. I shudder at the thought of trying to implement these sort of smarts in TH.

Ugh, well that's depressing. I suppose this also makes the naughty record selector check nigh impossible to get right as well. What's the right thing to do here—should we just ditch the ability to filter out naughty record selectors, and warn users of the danger in the Haddocks?

**Comment by goldfirere** [comment]
Is there a conservative naughtiness check? That is, a check that with no false-positives? I wouldn't want to accidentally filter out a selector that really should exist, but perhaps we can fail to filter out one that shouldn't. My preference in this direction is that failing to filter will lead to a type error right away, while filtering overeagerly will silently do the wrong thing, perhaps confounding downstream clients. And then we update the docs to describe the situation.

**Comment by RyanGlScott** [comment]
> Is there a conservative naughtiness check? That is, a check that with no false-positives? I wouldn't want to accidentally filter out a selector that really should exist, but perhaps we can fail to filter out one that shouldn't.

Good question. For what it's worth, not even the current naughtiness check satisfies this conservative property, as demonstrated by this example:

```
λ> putStrLn $([d| data S (a :: k) = MkS { getS :: Proxy (a :: k) } |] >>= dsDecs >>= \[DDataD _ _ s [DKindedTV a k] cons _] -> getRecordSelectors (DConT s `DAppT` DSigT (DVarT a) k) cons >>= stringE . show)
[DSigD getS_6989586621679083894 (DForallT [DPlainTV k_6989586621679083895,DPlainTV a_6989586621679083896] [] (DAppT (DAppT DArrowT (DAppT (DConT S_6989586621679083892) (DSigT (DVarT a_6989586621679083896) (DVarT k_6989586621679083895)))) (DAppT (DConT Data.Proxy.Proxy) (DSigT (DVarT a_6989586621679083896) (DVarT k_6989586621679083895))))),DFunD getS_6989586621679083894 [DClause [DConPa MkS_6989586621679083893 [DVarPa field_6989586621679083897]] (DVarE field_6989586621679083897)]]
λ> putStrLn $([d| data S a = MkS { getS :: Proxy (a :: k) } |] >>= dsDecs >>= \[DDataD _ _ s [DPlainTV a] cons _] -> getRecordSelectors (DConT s `DAppT` DVarT a) cons >>= stringE . show)
[]
```

If we write the data type as `data S (a :: k) = MkS { getS :: Proxy (a :: k) }`, then `getRecordSelectors` is OK with it, since `fv(Proxy (a :: k))` is a subset of `fv(S (a :: k))`. But if we write the data type as `data S a = MkS { getS :: Proxy (a :: k) }`, then that property doesn't hold anymore. So kind variables seem to be a challenge here.

Something that might work is to (1) ditch the `DType` argument of `getRecordSelectors`, and (2) instead check if all the type variables (_excluding_ kind variables) in the type of each record selector occur in the return type of the constructor. This would certainly fail to filter out all naughty record selectors, but I don't believe there'd be any false positives... I think.

**Comment by goldfirere** [comment]
What about:

```
data S k (a :: k)
data T a where
  MkT :: { foo :: Proxy (a :: k), bar :: S k a } -> T a
```

We can't tell that `k` is a kind variable in `bar`'s type. `bar` is not naughty, but I think your proposed check would filter it out.

**Comment by RyanGlScott** [comment]
Ugh, you're absolutely right. In that case, I'm quite out of ideas as to how to make this work.

**Comment by goldfirere** [comment]
I think we can't. So we shouldn't try anything fancy. Simply not filtering out naughty selectors means that types with naughty selectors can't be desugared, which is annoying. Instead, I propose this: filter out selectors that are obviously syntactically naughty. That is, filter out anything where some variable appears in the field type that does not appear in the result type -- without caring about kinds, etc. (I know this is not the conservative check I was seeking.) Advertise this design decision (somewhere -- I don't know where) and then be done with it. If a user gets unexpected behavior, I believe they can always tweak their definition to get th-desugar to do the right thing with its dumb-but-predictable syntactic check.

**Comment by RyanGlScott** [comment]
From https://github.com/goldfirere/th-desugar/issues/68#issuecomment-327949936:

> > Should we store the return kind of a datatype as `Maybe DKind` or `DKind`? 
> 
> Good question. I think it should be `Maybe DKind`, because the presence/absence of a kind signature can change whether GHC thinks the type has a CUSK.

As a certain Haskeller from Iceland informed me, there's another reason why you'd want `Maybe DKind`: there are some programs that you can express with the old syntax that you can't easily express with the new, kind-signature syntax. For instance, you can write this:

```haskell
newtype MyReaderT1 r m a where
  MyReaderT1 :: ReaderT r m a -> MyReaderT1 r m a
  deriving (Functor, Applicative, Monad, MonadReader r)
```

This works precisely because the `r` is brought into scope from `newtype MyReaderT1 r m a`. If we attempt to replace `r m a` with the equivalent kind signature:

```haskell
newtype MyReaderT2 :: Type -> (Type -> Type) -> Type -> Type where
  MyReaderT2 :: ReaderT r m a -> MyReaderT2 r m a
  deriving (Functor, Applicative, Monad, MonadReader r)
```

Then it fails, as GHC will attempt to derive an instance for `MonadReader r (MyReaderT2 r2 m)` (for fresh type variables `r2` and `m`), but the `MonadReader` instance for `ReaderT`:

```haskell
instance MonadReader r m => MonadReader r (ReaderT r m)
```

Demands that `r ~ r2`. So it turns out there _are_ legitimate reasons why you'd want to keep the old syntax around after all!

**Comment by RyanGlScott** [comment]
I've opened #74 to implement this.
