### ISSUE TITLE
Remove DStarT?

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/th-desugar#69]
Currently, `DType` has a distinguished constructor for `*` called `DStarT`. But this is a somewhat questionable choice, given that:

* We could just as easily encode this with `DConT (mkName "*")` (or `DConT ''Type`, on more recent GHCs).
* We are moving in the direction of [embracing `Type` over `*`](https://github.com/ghc-proposals/ghc-proposals/pull/83) in the (perhaps not-so-distant) future.

In light of this, perhaps we ought to simply just remove `DStarT`. This should be a relatively straightforward change save for one complication: we cannot sweeten `DConT (mkName "*")` back to `ConT (mkName "*")` on GHC 7.6 due to an [old bug](https://ghc.haskell.org/trac/ghc/ticket/7667), as this program witnesses:

```haskell
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE TemplateHaskell #-}
module Bug where

import Language.Haskell.TH.Syntax

$(let starKindName :: Name
      starKindName = mkNameG_tc "ghc-prim" "GHC.Prim" "*"
   in do foo <- newName "foo"
         return [ SigD foo (SigT (ConT ''Bool) (ConT starKindName))
                , ValD (VarP foo) (NormalB (ConE 'True)) []
                ])
```
```
$ /opt/ghc/7.6.3/bin/ghc Bug.hs
[1 of 1] Compiling Bug              ( Bug.hs, Bug.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package array-0.4.0.1 ... linking ... done.
Loading package deepseq-1.3.0.1 ... linking ... done.
Loading package containers-0.5.0.0 ... linking ... done.
Loading package pretty-1.1.1.0 ... linking ... done.
Loading package template-haskell ... linking ... done.

Bug.hs:7:3:
    Illegal type constructor or class name: `*'
    When splicing a TH declaration:
      foo_0 :: GHC.Types.Bool :: GHC.Prim.*
```

We'd just have to sweeten it back to `StarT` on GHC 7.6.

**Comment by goldfirere** [comment]
How would this affect `singletons`? Whenever I've wondered about a design decision in `th-desugar`, I've answered it by deciding what the author of `singletons` would like. I recognize that this may not be fair to other users of `th-desugar` -- and you should post such questions here to get their feedback -- but history has suggested that these other users, if they exist, tend not to opine here much.

In general, I support this, as I think dropping support for GHC 7.6 is reasonable at this point.

**Comment by RyanGlScott** [comment]
> How would this affect `singletons`?

Are you asking how this would affect `singletons`-the-library? If so, not much at all. Grepping for `DStarT` within the `singletons` only yields 11 hits, of which:

* Two are used in pattern-matching (which could be replaced with an equivalent pattern guard à la `(DConT n) | n == ''Type`).
* The rest are used in expression position (and again, could be easily replaced with `DConT ''Type`).

Perhaps I'm misunderstanding your question, though.

> In general, I support this, as I think dropping support for GHC 7.6 is reasonable at this point.

To be clear, we needn't drop support for GHC 7.6 at all with this change. We'd just have to add some extra CPP to make it work (to which `th-desugar` is certainly no stranger).

**Comment by goldfirere** [comment]
Right.

Then proceed. :)
