### ISSUE TITLE
Travis tests an excessive number of GHCs

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/th-desugar#91]
Currently, we test every single point release of GHC from 7.6.3 to the present day. This results in much longer Travis iteration times in exchange for benefits that aren't exactly clear to me. @goldfirere, couldn't we get away with just testing the latest point release from each major series (i.e., 7.6.3, 7.8.4, 7.10.3, 8.0.2, 8.2.2, 8.4.3, 8.6.1, and HEAD)?

**Comment by goldfirere** [comment]
Yes, I think that's an improvement.
