### ISSUE TITLE
Locally reified classes have extraneous class contexts

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/th-desugar#99]
While working towards #90, I discovered an oddity in the way that `Language.Haskell.TH.Desugar.Reify` works. Consider the following example:

```haskell
#!/usr/bin/env cabal
{- cabal:
build-depends: base, template-haskell, th-desugar
-}
{-# LANGUAGE TemplateHaskell #-}
module Main where

import Language.Haskell.TH
import Language.Haskell.TH.Desugar

main :: IO ()
main = putStrLn
 $([d| class C a where
         method :: a
     |] >>= \ds -> withLocalDeclarations ds (dsReify (mkName "C")) >>= stringE . show)
```
```
$ cabal new-run Bug.hs                                                                             
Resolving dependencies...                                                                          
Build profile: -w ghc-8.6.3 -O1                                                                    
<elided>
Just (DTyConI (DClassD [] C_6989586621679042639 [DPlainTV a_6989586621679042641] [] [DLetDec (DSigD method_6989586621679042640 (DForallT [DPlainTV a_6989586621679042641] [DAppPr (DConPr C_6989586621679042639) (DVarT a_6989586621679042641)] (DVarT a_6989586621679042641)))]) (Just []))
```

After some cleanup, that's:

```haskell
class C a where
  method :: forall a. C a => a
```

Notice how local reification has _added_ the `forall a. C a =>` part! This is because of the (rather strangely named) `stripClassDec` function:

https://github.com/goldfirere/th-desugar/blob/cb8092fb68d9214bf8ed5e18a6d1ca061db6453e/Language/Haskell/TH/Desugar/Reify.hs#L428-L439

It's rather odd that we go through the effort of adding this extra `forall` and class context, since it's wrong to do so in the first place! The only conceivable reason that I can think of for doing this is that due to an old GHC bug ([Trac #15551](https://ghc.haskell.org/trac/ghc/ticket/15551)), GHC itself used to reify type classes with this extra `forall`/context in front of each method, so this hack might have used to make local reification match the behavior of GHC reification in the `th-desugar` test suite.

Now that Trac #15551 has been fixed in the upcoming GHC 8.8 release, however, this means that local reification (which adds this extra `forall`/context) no longer matches the behavior of GHC reification (which doesn't). I propose that we just change local reification to no longer add these extraneous `forall`s/contexts, and modify the test suite to work around Trac #15551 on old GHCs.

**Comment by goldfirere** [comment]
But won't the suggested change cause problems for users who use th-desugar with older GHCs? th-desugar's local reification mechanism and the built-in one should return the same results.

**Comment by RyanGlScott** [comment]
Ah, that's a good point. Still, Trac #15551 being fixed means that GHC will reify type classes differently before 8.8 (with the extraneous `forall`/context) and after 8.8 (without it). Should we change `Language.Haskell.TH.Desugar.Reify` to match this behavior, but only on GHC 8.8+?

**Comment by goldfirere** [comment]
Hm. th-desugar's reification interface returns TH stuff (as opposed to th-desugar stuff). Therefore, it's only natural that it conforms to whatever GHC does, in any GHC release. This means that th-desugar might produce different behavior between (GHC) versions, but I think that's OK. We haven't promised not to. (th-abstraction has.)

So: My vote would be to keep the current behavior for GHC < 8.8 but echo GHC's change for GHC 8.8.
